-- Archived audit logs table for retention policy archiving
CREATE TABLE archived_audit_logs (
    id BINARY(16) PRIMARY KEY,
    workspace_id BINARY(16) NOT NULL,
    actor_id BINARY(16) NOT NULL,
    actor_email VARCHAR(100),
    actor_name VARCHAR(100),
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    resource_name VARCHAR(255),
    metadata JSON,
    previous_state JSON,
    new_state JSON,
    ip_address VARCHAR(50),
    user_agent VARCHAR(255),
    session_id VARCHAR(50),
    severity ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL,
    category ENUM('AUTHENTICATION', 'AUTHORIZATION', 'DATA_ACCESS', 'DATA_MODIFICATION', 'CONFIGURATION', 'SECURITY', 'COMPLIANCE', 'SYSTEM') NOT NULL,
    created_at TIMESTAMP NOT NULL,
    archived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_by_policy_id BINARY(16) NOT NULL,
    INDEX idx_archived_workspace (workspace_id),
    INDEX idx_archived_actor (actor_id),
    INDEX idx_archived_action (action),
    INDEX idx_archived_resource (resource_type, resource_id),
    INDEX idx_archived_created (created_at),
    INDEX idx_archived_policy (archived_by_policy_id),
    INDEX idx_archived_at (archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
